from sqlalchemy.orm import DeclarativeBase, mapped_column, Mapped
from sqlalchemy import String, Integer, Float, Date, Time, Numeric
from typing import Optional

class Base(DeclarativeBase):
    pass

class SilverRawData(Base):
    __tablename__ = 'raw_data'
    __table_args__ = {'schema': 'silver'}

    unnamed_0: Mapped[int] = mapped_column(Integer, primary_key=True)
    resultid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    raceid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    driverid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    constructorid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    statusid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    number: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    grid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    position: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    positiontext: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    positionorder: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    points: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    laps: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    time: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    milliseconds: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    fastestlap: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    rank: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    fastestlaptime: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    fastestlapspeed: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    year: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    round: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    circuitid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    name_x: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    date: Mapped[Optional[Date]] = mapped_column(Date, nullable=True)
    time_races: Mapped[Optional[Time]] = mapped_column(Time, nullable=True)
    url_x: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    fp1_date: Mapped[Optional[Date]] = mapped_column(Date, nullable=True)
    fp1_time: Mapped[Optional[Time]] = mapped_column(Time, nullable=True)
    fp2_date: Mapped[Optional[Date]] = mapped_column(Date, nullable=True)
    fp2_time: Mapped[Optional[Time]] = mapped_column(Time, nullable=True)
    fp3_date: Mapped[Optional[Date]] = mapped_column(Date, nullable=True)
    fp3_time: Mapped[Optional[Time]] = mapped_column(Time, nullable=True)
    quali_date: Mapped[Optional[Date]] = mapped_column(Date, nullable=True)
    quali_time: Mapped[Optional[Time]] = mapped_column(Time, nullable=True)
    sprint_date: Mapped[Optional[Date]] = mapped_column(Date, nullable=True)
    sprint_time: Mapped[Optional[Time]] = mapped_column(Time, nullable=True)
    circuitref: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    name_y: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    location: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    country: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    lat: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    lng: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    alt: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    url_y: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    driverref: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    number_drivers: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    code: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    forename: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    surname: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    dob: Mapped[Optional[Date]] = mapped_column(Date, nullable=True)
    nationality: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    url: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    constructorref: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    nationality_constructors: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    url_constructors: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    lap: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    position_laptimes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    time_laptimes: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    milliseconds_laptimes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    stop: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    lap_pitstops: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    time_pitstops: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    duration: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    milliseconds_pitstops: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    driverstandingsid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    points_driverstandings: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    position_driverstandings: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    positiontext_driverstandings: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    wins: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    constructorstandingsid: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    points_constructorstandings: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    position_constructorstandings: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    positiontext_constructorstandings: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    wins_constructorstandings: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    status: Mapped[Optional[str]] = mapped_column(String, nullable=True)