CREATE_SCHEMA = """
CREATE SCHEMA IF NOT EXISTS bronze;
"""

CREATE_RAW_DATA = """
CREATE TABLE IF NOT EXISTS bronze.raw_data (
    unnamed_0                           TEXT,
    resultid                            TEXT,
    raceid                              TEXT,
    driverid                            TEXT,
    constructorid                       TEXT,
    number                              TEXT,
    grid                                TEXT,
    position                            TEXT,
    positiontext                        TEXT,
    positionorder                       TEXT,
    points                              TEXT,
    laps                                TEXT,
    time                                TEXT,
    milliseconds                        TEXT,
    fastestlap                          TEXT,
    rank                                TEXT,
    fastestlaptime                      TEXT,
    fastestlapspeed                     TEXT,
    statusid                            TEXT,
    year                                TEXT,
    round                               TEXT,
    circuitid                           TEXT,
    name_x                              TEXT,
    date                                TEXT,
    time_races                          TEXT,
    url_x                               TEXT,
    fp1_date                            TEXT,
    fp1_time                            TEXT,
    fp2_date                            TEXT,
    fp2_time                            TEXT,
    fp3_date                            TEXT,
    fp3_time                            TEXT,
    quali_date                          TEXT,
    quali_time                          TEXT,
    sprint_date                         TEXT,
    sprint_time                         TEXT,
    circuitref                          TEXT,
    name_y                              TEXT,
    location                            TEXT,
    country                             TEXT,
    lat                                 TEXT,
    lng                                 TEXT,
    alt                                 TEXT,
    url_y                               TEXT,
    driverref                           TEXT,
    number_drivers                      TEXT,
    code                                TEXT,
    forename                            TEXT,
    surname                             TEXT,
    dob                                 TEXT,
    nationality                         TEXT,
    url                                 TEXT,
    constructorref                      TEXT,
    name                                TEXT,
    nationality_constructors            TEXT,
    url_constructors                    TEXT,
    lap                                 TEXT,
    position_laptimes                   TEXT,
    time_laptimes                       TEXT,
    milliseconds_laptimes               TEXT,
    stop                                TEXT,
    lap_pitstops                        TEXT,
    time_pitstops                       TEXT,
    duration                            TEXT,
    milliseconds_pitstops               TEXT,
    driverstandingsid                   TEXT,
    points_driverstandings              TEXT,
    position_driverstandings            TEXT,
    positiontext_driverstandings        TEXT,
    wins                                TEXT,
    constructorstandingsid              TEXT,
    points_constructorstandings         TEXT,
    position_constructorstandings       TEXT,
    positiontext_constructorstandings   TEXT,
    wins_constructorstandings           TEXT,
    status                              TEXT
);
"""